#General
work dir: data
slimfile: timesweeper_model.slim 

scenarios: ["neut", "sdn", "ssv"]
mut types: [2]
num_sample_points: 10
sample sizes: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
inds_per_tp: 100
ploidy: 2
win_size: 51
physLen: 1000000


#Simulation
reps: 20
slim path: slim
